[package]
name = "include_str"
description = "Include UTF-8 files with compile-time trimming and SQL preprocessing"
version = "0.0.1"
edition = "2024"
rust-version = "1.85"
readme = "README.md"
# repository = ""
# license = "" # e.g. `Apache-2.0`
# categories = []
# keywords = []
# documentation = "" # Alternative documentation
# rust-version = "" # Min required rust version

[dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"] # Used in the root .rs file to enable `#![cfg_attr(docsrs, feature(doc_cfg))]`
